### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by rjft197** [Code-Sharp/WampSharp#221] opened 2017-11-29 06:22 UTC
I'm sure I'm doing something wrong.  I'm using Visual Studio 2015, I create a brand new project.  I've then followed the instructions from your site here
http://wampsharp.net/wamp2/getting-started-with-wampv2/
and used nuget to install it.

However when I use a IWampRealProxy to GetSubject and Subscribe as I've seen there is an error

The type 'ISubject<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reactive.Interfaces, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.

In the solution explorer i check and it says there is a reference to System.Reactive however it's runtime version v4.0.30319

Any chance you could help me out and let me know what I'm doing wrong.  I looked around and have seen a few things which look like similar issues and it's suggested installing a different version of System.Reactive, however I'm not sure how to go about that as it was all done automatically by NuGet.  This may be the wrong spot to ask this question if so please do direct me to the right place and I'll have a ask there.

**Comment by darkl** [comment] 2017-11-29 11:35
Go to the updates tab in NuGet explorer and manually choose to update
System.Reactive to a lower version. You might need to update your
app.config and remove the assembly binding inserted there.

I tried fixing this by specifying an upper bound for System.Reactive which
is lower than 4, but that doesn't seem to work.

Elad

**Comment by darkl** [comment] 2017-12-21 04:49
Duplicate of #196.

**Closed by darkl** 2017-12-21 04:49 UTC
