### ISSUE TITLE
router to router communication

### ISSUE THREAD

**Issue by gtaranas** [Code-Sharp/WampSharp#88] opened 2015-07-08 08:27 UTC
Hi Elad,

I was wondering if there is any way for router to router communication (a crossbar.io internet router transfers raw wamp messages direct to wampsharp intranet router)

**Comment by darkl** [comment] 2015-07-08 11:53
Hi @gtaranas,

I think I need some more details for what you're trying to do. 

Do you want the external router (crossbario) to simply forward all requests to the internal router (WampSharp)?

**Comment by gtaranas** [comment] 2015-07-08 12:13
yes something like that, 

We have intranet clients connected to wampsharp router and public internet clients connected to crossbar and we need a way for example an intranet peer (a publisher) to publish messages to public peer (subscriber). but without intranet client directly connect to public router.

**Comment by darkl** [comment] 2015-07-08 12:21
Can't you implement this specific scenario with a WampSharp subscriber that subscribes to the specific topic and publishes messages to the external router topic (using a WampChannel)?

**Comment by gtaranas** [comment] 2015-07-08 12:28
The two peers is connected to different router-server and we don't want internal client to directly connect to public router.

**Comment by darkl** [comment] 2015-07-08 12:33
You can install the forwarding Subscriber inside the WampSharp router: Write a subscriber that publishes its events to a topic in the external router (using a WampChannel). Then subscribe to the same topic in the internal router application (using RealmContainer.GetRealmByName() Services).

Would that work for you?

**Comment by gtaranas** [comment] 2015-07-08 12:53
yes, was the first thought crossed my mind, but what happens if i don't want to make changes to internal router every time a new feature (subscriber) added, i need to leave this job to peers (like in the normal peer-router-peer communication). we need something more low level communication: peer-public_router-internal_router-peer.

**Comment by darkl** [comment] 2015-07-08 14:12
You can subscribe to the Realm.TopicContainer.TopicCreated event to get notified when a new topic was created. Then you can subscribe dynamically to these topics. (and get the events as JSON objects)

**Comment by gtaranas** [comment] 2015-07-08 14:25
And what about rpc's that needs to be register to router?

**Comment by darkl** [comment] 2015-07-08 14:38
It's more complicated. I think I still don't understand entirely your request.
Do you want also the external router procedures to be accessible from internal router peers?

**Comment by gtaranas** [comment] 2015-07-09 06:45
Yes i need a full two way communication both rpc and pubsub between internal wampsharp peers and external crossbar peers. is this possible?

**Comment by darkl** [comment] 2015-07-09 07:22
I need to think about this.
But can you explain why do you need both routers? Why not just use the same router for all peers? (for example the crossbar router)
I think I don't get it, why use two routers if all topics/procedures should be accessible from both routers?

**Comment by gtaranas** [comment] 2015-07-09 07:36
We need some topics/procedures not all to be accessible from both routers and we also have many reasons why we need two routers (internal and external) and the internal router must be in .net (wampsharp). Anyway thank's for your time.

**Comment by darkl** [comment] 2015-07-09 07:58
The problem is I feel the of details: the best solution I have right now in my mind is something that forwards every message to the crossbar router (and somehow correlates responses to the right client) - but that will be eventually equivalent to run all peers on the crossbar router! which you stated that you don't want.
In order to find an appropriate solution to the problem I need details - "There are many reasons why we need two routers" does not help much.

**Comment by gtaranas** [comment] 2015-07-09 08:34
The main reasons we need two routers:
1) Isolation between public and private (external - internal)
2) Internal router must be windows service running in .net (as a part of an existing ecosystem)
3) External router leverages crossbar.io benefits.

A basic scenario of router to router communication that we need is:
a) An internal peer (callee) register rpc in internal router.
b) Internal router register this rpc to the public router also.
c) A public peer calls the rpc registered in public router.
d) Internal router somehow redirects the call message to internal peer.

**Comment by darkl** [comment] 2015-07-09 08:38
Great, so I'll think of a solution that forwards internal router procedure
registrations/topic publications to the external router. Will that be good
enough for you?

**Comment by gtaranas** [comment] 2015-07-09 09:13
Yes, i think. how this can be done from library will this be an extension or something?

**Comment by darkl** [comment] 2015-07-09 09:24
It will be external to the library. I think I'll post here some gist draft
or something after working on this (assuming this won't be too much
difficult).

**Comment by gtaranas** [comment] 2015-07-09 09:27
Thank you so much Elad.

**Comment by darkl** [comment] 2015-07-09 14:17
Hi @gtaranas,

I implemented a very simple version of this [here](https://gist.github.com/darkl/3e3d9177cd37225a3923). It uses the customized RealmContainer feature which is not documented. (and will probably be modified a few more times in the future)

My implementation doesn't handle any reconnections and other edge cases. The important stuff happens in ForwardingTopicContainer's Publish methods and ForwardingRpcCatalog Register method.

Hope it helps,
Elad

**Comment by gtaranas** [comment] 2015-07-10 06:38
Thank you for your time, i will let you know soon.

**Comment by gtaranas** [comment] 2015-07-10 10:45
Elad, you saved me!!!  that's exactly what I need.

One Little Note:
The rpc call works fine but the publication from external client does not reach the internal client subscription. so i end up with this small change inside ForwadingTopicContainer:

public IDisposable Subscribe(IWampRawTopicRouterSubscriber subscriber, string topicUri, SubscribeOptions options)
        {
            var intDisposable = mTopicContainer.Subscribe(subscriber, topicUri, options);

            var extDisposable = mExternalRouterChannel.RealmProxy.Services.GetSubject(topicUri).Subscribe(x =>
            {
                mTopicContainer.Publish(WampObjectFormatter.Value, new PublishOptions
                {
                    Acknowledge = true,
                    DiscloseMe = true
                }, topicUri);
            });
            return new CompositeDisposable { intDisposable, extDisposable };
        }

it works, but is this right? you have a better implementation?

**Comment by darkl** [comment] 2015-07-10 11:39
Your implementation omits the published event's content.
I'd implement this also with raw api: using IWampTopicProxy and writing an adapter between IWampRawTopicRouterSubscriber and IWampRawTopicClientSubscriber that does something similar to what you wrote in the rx handler.

Another note: this can actually create circular publications since you might subscribe to a topic you publish to. In order to avoid this, you should set the forwarded PublishOptions (in Publish methods) to have ExcludeMe = true (this is the default, but a client might request ExcludeMe = false in by that create a publication loop).

**Comment by darkl** [comment] 2015-07-10 13:23
Another note: you should publish in your event handler to the topic specified in the EventDetails, otherwise you won't publish to the right topic in the case of pattern-based subscriptions.

**Comment by gtaranas** [comment] 2015-07-10 13:47
you mean something like this; (x.Details.Topic instant of topicUri) i also add x.arguments to prevent omit published event's content

var extDisposable = mExternalRouterChannel.RealmProxy.Services.GetSubject(topicUri).Subscribe(x=>
            {
                mTopicContainer.Publish(WampObjectFormatter.Value, new PublishOptions
                {
                    Acknowledge = true,
                    DiscloseMe = true
                }, x.Details.Topic, x.Arguments);
});

**Comment by darkl** [comment] 2015-07-10 14:38
Yeah but I rather implement this using the raw api: the subscribe method
gets a subscriber parameter: wrap it in an adapter class and call
RealmProxy.TopicContainer.GetTopicByUri().Subscribe(wrappedSubscriber,
options)

**Comment by darkl** [comment] 2015-09-15 21:23
Closing since it seems to be resolved.

**Closed by darkl** 2015-09-15 21:23 UTC
Labels: question, router
