### ISSUE TITLE
WampSharp <=> Crossbar over RawSocket transport

### ISSUE THREAD

**Issue by Altern8** [Code-Sharp/WampSharp#90] opened 2015-07-17 21:24 UTC
I have implemented a router component in C++ (using AutobahnCpp) that provides telemetry services for a large M2M solution. This C++ component is hosted on a Crossbar router (AutobahnPyton) and relies on RawSocket for its transport layer. The goal is to provide a mean for C# applications (using WampSharp) to invoke remote procedures using the WebSocket protocol.

After trying many attempts in establishing a connection with the Crossbar router, I realized that 
my WampSharp client was specifying an invalid magic byte during the handshake process.

    [Router      10067] WampRawSocketProtocol: connection made
    [Router      10067] WampRawSocketProtocol: opening handshake received - 47455420
    [Router      10067] WampRawSocketProtocol: invalid magic byte (octet 1) in opening handshake: was 0x47, but expected 0x7f
    [Router      10067] Unhandled Error

By looking at the documentation, I saw that the WampRawSocketProtocol base class (a Twisted-based WAMP-over-RawSocket) expects the magic byte (octet 1) to be 0x7f for opening the handshake. I also found that you've already thought of adding RawSocket support for [client connectivity] (https://github.com/Code-Sharp/WampSharp/issues/69).

So, I'm wondering if it is feasible for a WampSharp client (WampChannel) to establish a raw TCP connection (using RawSoscket and MsgPack) to a Crossbar router. 

If possible, it would be great to have some code snippets that show how to install the WampSharp.RawSocket package and how to implement the client connection.

**Comment by darkl** [comment] 2015-07-17 21:54
Hi @Altern8,

WampSharp currently implements only router raw-socket support. Additionally, WampSharp implements the original raw-socket version (before [revision](https://github.com/tavendo/AutobahnPython/issues/291)).

At the time I implemented this version, AutobahnPython and AutobahnCpp had an implementation only for the original raw-socket specification and not for the revised version. I see that the revised version is now implemented, this should be addressed in WampSharp also. Sorry you wasted your time trying to connect incompatible implementations.

Regarding the client implementation, we need to think how to implement it so that the same code is reused for client and router parts. The problem is the SuperSocket seems to have no client library that supports the same interfaces (IReceiveFilterFactory, IReceiveFilter). Maybe another library/different implementation should be considered.

Elad

**Comment by darkl** [comment] 2015-09-16 22:22
Hi @Altern8,

I've released a version of a RawSocket client to MyGet feed.

You are welcome to try it.

In order to try it, you need to add a package source to https://www.myget.org/F/wampsharp/api/v2 (Tools -> NuGet Package Manager -> Package Manager Settings -> Packages Sources -> + button)

Then just install WampSharp.RawSocket. The api is quite new, you can see a usage sample [here](https://gist.github.com/darkl/1acee3b4f527a23828c6#file-rawsocketsample-cs-L23).

Elad

**Closed by darkl** 2015-09-16 22:22 UTC
Labels: client, rawsocket, router
