### ISSUE TITLE
StackOverflowException

### ISSUE THREAD

**Issue by darkl** [Code-Sharp/WampSharp#92] opened 2015-08-24 16:52 UTC
(Related to #91, @nj4x)

Instructions how to reproduce:

Use [this client](https://gist.github.com/darkl/ab4003af525c4eb2500a) and [this router](https://gist.github.com/darkl/bdbc6b97299d72eb32c8) code.

Open a few (~3) tabs of the client in Chrome. Then open one client's Console. Close that client after the numbers in the Console get updated a few times. The Router will terminate with StackOverflowException.

Seems that the Exception is due to the ActionBlock implementation. Consider using Tpl Dataflow instead of this rx alternative.

**Comment by darkl** [comment] 2015-08-24 19:23
Seems that Observable.Merge is implemented using recursion. If the queue is large enough, it causes a StackOverflowException.

**Comment by nj4x** [comment] 2015-08-24 21:11
Hi Elad,

Please check https://github.com/nj4x/WampSharpTests.git project.
I've tried to collect multiple WampSharp issues in the single application.
You just need to download it and run to reproduce (note case 2 & 3 are
fixed in 1.2.2.53-dev)

Acc. to StackOverflow error - I think that changing rx to alternative will
result in other memory issues due to inability of Publisher to control over
the rate it publishes events.
Publisher should be able to check (in some way) pending events queue size
to detect and handle congestions. Is it possible to apply some
acknowledgement mechanisms without affecting performance and keeping
Publishers interface as simple as ((ISubject<T>) _subject).OnNext(evt); ?

**Comment by darkl** [comment] 2015-08-24 21:26
Hi @nj4x,

Thanks for the test project, I'll try to run it sometimes this week (probably in the weekend or so). I think you should still create an issue per problem so it would easier (for both of us) to track their statuses and discuss them separately.

About the queue stuff - queues will stay individual per client, so I don't find a lot of sense in exposing queue size to library users. I might consider making the ActionBlock mechanism plugable so users can have control on how items are queued per client, though I don't really like this.

Elad

**Closed** 2015-09-15 21:21 UTC
Labels: bug, router
