### ISSUE TITLE
publishing stops to work without any exception or any message

### ISSUE THREAD

**Issue by simpuc** [Code-Sharp/WampSharp#125] opened 2016-03-01 11:37 UTC
Hello,
I am using wampsharp with crossbar.io to publish/subscribe from/to excel.

The code to connect is:
`
factory = new DefaultWampChannelFactory();
channel = factory.CreateJsonChannel();

services = channel.RealmProxy.Services;

monitor = channel.RealmProxy.Monitor;
monitor.ConnectionBroken += OnClose;
monitor.ConnectionError += OnError;
monitor.ConnectionEstablished += OnConnection;

 Func<Task> connect = async () =>
            {
                await channel.Open();
            };

WampChannelReconnector reconnector = new WampChannelReconnector(channel, connect);
reconnector.Start();
`

The code to publish is:
`        
// publications is a dictionary that contains the ISubject for all the topic the application is publishing
Dictionary<string, ISubject<Payload>> publications = new Dictionary<string, ISubject<Payload>>();

ISubject<Payload> publisher;
if (publications.ContainsKey(topic)) {
    // get the ISubject for the topic already subscribed
    publisher = (ISubject<Payload>)publications[subject];
}
else {
    // get the ISubject for a topic NOT already subscribed
    publisher = services.GetSubject<Payload>(topic);
    publications[topic] = publisher;
}

// publish next value
publisher.OnNext(payload);
`
It works well for some hours, then it stops to work without any exception or any message. It simply do not publish anymore the updated values for all the topics.
If I restart the crossbar server all restart well.

How can I find where is the error?

Thank you for your help.

Simone

**Comment by darkl** [comment] 2016-03-01 12:59
Hi Simone,

Please trying enabling logs on debug mode and try to check if you can see anything interesting in the log file when publications fail.

Elad

**Comment by simpuc** [comment] 2016-03-02 09:50
Hi Elad,

I have enabled logs on debug on crossbar server. It didn't show anything.
The publisher stopped to work at 18:09:37 with no signal, no error on logs, no error or exception in Excel.
Is it possible to logs on debug mode also WampSharp? If I debug it by VS2013 I see **services ** up and running. 
Should I define an IPayloadSubject and overload the method onError?
Thank you for your help

Simone

**Comment by darkl** [comment] 2016-03-02 12:04
Hi,

You can subscribe to OnError of Subject.

I advise you anyway to enable Logs on Debug level: just install log4net and
enable all logs from WampSharp namespace on debug level. You should also
define a file appender so logs will be written to a file. (You can find
plenty log4net tutorials by Googling)

Elad

**Comment by simpuc** [comment] 2016-03-08 07:56
Hi,

I have set up log4net.
In the meantime I have tried to publish using the following code:
`           // get topicProxy
                IWampTopicProxy topicProxy;
                if (publications.ContainsKey(subject))
                {
                    topicProxy = publications[subject];
                }
                else
                {
                    topicProxy = channel.RealmProxy.TopicContainer.GetTopicByUri(subject);
                    publications[subject] = topicProxy;
                }
                // create a publication task
                Task<long?> publishTask = topicProxy.Publish
                        (new PublishOptions { Acknowledge = Configuration.Instance.Publication_Acknowledge}, payload.serialization());
                // try to publish within timeout millisec 
                bool inTime = publishTask.Wait(Configuration.Instance.Publication_timeout_ms);`

I thought  that using the ack capabilities could help me to debug the problem. 

The program have the same behavoiur, the publisher stopped to work around  18:00 with no signal, no error on logs, no error or exception in Excel. The bool variable inTime is false (wait is 20 ms) for all the topics and the subscriptions continue to work well.

Why it stops around 18:00? The flow of data to be published stops around 18.00 and publication works well until around 18.00. Then, for some reason, it do not restart in the morning.

I have tried two two different machines and thay had the same behaviour.

I will continue the investigation using log4net.

Keep in touch and thank you for your work

Simone

**Comment by darkl** [comment] 2016-03-08 08:05
Hi Simone,

Do you have any DEBUG logs after 18:00?

Elad

**Comment by simpuc** [comment] 2016-03-09 08:59
Hi Elad,

These are logs this morning at  08:25 when I tried to publish again the TOPIC 'TESTTOPIC' :

2016-03-09 08:25:17,506 [VSTA_Main] DEBUG [WampSharp.Core.Proxy.WampOutgoingRequestSerializer`1[[Newtonsoft.Json.Linq.JToken, Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]]]   Calling remote peer proxy method: Void Publish(Int64, WampSharp.V2.Core.Contracts.PublishOptions, System.String, System.Object[])

2016-03-09 08:25:17,506 [VSTA_Main] DEBUG [WampSharp.Core.Proxy.WampOutgoingRequestSerializer`1[[Newtonsoft.Json.Linq.JToken, Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]]]   Calling remote peer proxy method: Void Publish(Int64, WampSharp.V2.Core.Contracts.PublishOptions, System.String, System.Object[])

2016-03-09 08:25:17,508 [VSTA_Main] DEBUG [WampSharp.Newtonsoft.JTokenMessageParser]   Formatted message [16,713489078514019,{},"TESTTOPIC",[{"value":92.0,"datatype":"double","timestamp":"2016-03-09T08:25:17.5063414+01:00"}]]

2016-03-09 08:25:17,508 [VSTA_Main] DEBUG [WampSharp.Newtonsoft.JTokenMessageParser]   Formatted message [16,713489078514019,{},"TESTTOPIC",[{"value":92.0,"datatype":"double","timestamp":"2016-03-09T08:25:17.5063414+01:00"}]]

I tried also to watch the variable channel.RealmProxy.Monitor.isConnected and it was True.

I have checked also all the logs WampSharp have produced from 14.00 of yesterday to this morning.
There are only three kind of message:
WampSharp.Core.Dispatch.WampIncomingMessageHandler
WampSharp.Newtonsoft.JTokenMessageParser
WampSharp.Core.Proxy.WampOutgoingRequestSerializer

Today I am building one test case ad hoc. In the meantime I am becoming sad. Very sad.

Thank you 

Simone

**Comment by simpuc** [comment] 2016-03-09 09:06
Hi Elad,

to be more accurate I must say that this morning at 08:25 when I tried to publish again the TOPIC 'TESTTOPIC', it wasn't published.

Simone

**Comment by darkl** [comment] 2016-03-09 09:50
Hi Simone,

Due to the logs, the message is indeed sent. (We see the serialized JSON
value).

Can you check via crossbar logs if the serialized message is received to
router?

Elad

**Comment by simpuc** [comment] 2016-03-11 14:30
Hi Elad,

this is the last message from the server crossbar.io side.
2016-03-11T13:01:35+0100 [Container    7004 autobahn.twisted.websocket.WebSocketAdapterProtocol] WAMP RECV: message=Event(subscription=7380746152490804, publication=4494202260532649, args=[{u'datatype': u'double', u'timestamp': u'2016-03-11T13:01:35.46033+01:00', u'value': 0.5209268407609723}], kwargs=None, publisher=None, topic=quants.TEST_R_TO_L_25|ASK, enc_algo=None, enc_key=None, enc_serializer=None, payload=-), session=4414896192385477, authid=None

These are the last two messages from the client WAMPSHARP side
2016-03-11 13:01:35,461 [VSTA_Main] DEBUG [WampSharp.Newtonsoft.JTokenMessageParser]   Formatted message [16,261454128499215,{},"quants.TEST_R_TO_L_25|ASK",[{"value":0.52092684076097229,"datatype":"double","timestamp":"2016-03-11T13:01:35.46033+01:00"}]]
2016-03-11 13:01:35,461 [VSTA_Main] DEBUG [WampSharp.Newtonsoft.JTokenMessageParser]   Formatted message [16,261454128499215,{},"quants.TEST_R_TO_L_25|ASK",[{"value":0.52092684076097229,"datatype":"double","timestamp":"2016-03-11T13:01:35.46033+01:00"}]]

Then, the client WAMPSHARP continues to produce a lot of logs indicating that it is publishing.

Instead, the server side do not logs anything other from  the client WAMPSHARP, but the server continues to work well. Two python client works well for publish and subscribe and  the client WAMPSHARP continue to works well for subscribing.

So  I will investigate the problem  in the client side by I haven't any clever idea? Do you have? Could I try to build a client outside excel?

Thank you
Simone

**Comment by darkl** [comment] 2016-03-11 22:48
Hi Simone,

If you can create a small project that reproduces the issue, it might be useful.

I suspect this might be related to WebSocket4Net, though, it is similar to [this issue](https://github.com/kerryjiang/WebSocket4Net/issues/32).

Elad

**Comment by simpuc** [comment] 2016-03-17 11:21
Hi Elad,
the behavior of the issue about WebSocket4Net is very similar to this issue. Do you use WebSocket4Net  inside of WampSharp?

The code you find attached reproduces the issue. I run 3 or 4 instance of it and the issue rise in few minutes. 
I hope it will help you

Hearing from you soon :-)

Thank you
Simone

`using System;
using System.Collections;
using System.Collections.Generic;
using System.Reactive.Subjects;
using System.Threading.Tasks;
using WampSharp.Core.Listener;
using WampSharp.V2;
using WampSharp.V2.Client;
using WampSharp.V2.Core.Contracts;
using WampSharp.V2.Realm;
using WampSharp.V2.Rpc;

public class Test
{
    public class Payload
    {
        private dynamic _value;
        public dynamic value
        {
            get
            {
                if (datatype == "string") { return _value; }
                else if (datatype == "double") { return (double)_value; }
                else if (datatype == "int") { return (int)_value; }
                else if (datatype == "datetime")
                {
                    if (_value.GetType() == DateTime.Now.GetType())
                        return _value;
                    else if (_value is double)
                        return DateTime.FromOADate(_value);
                    else
                        try
                        {
                            return DateTime.Parse(_value);
                        }
                        catch (Exception e)
                        {
                            Console.WriteLine("Payload datetime exception " + e.Message);
                            return new DateTime();
                        }
                }
                else throw new Exception("Payload unkown type " + datatype);
            }
            set { _value = value; }
        }
        public string datatype { get; set; }
        public DateTime timestamp { get; set; }

        public Payload(dynamic value, string type, DateTime timestamp)
        {
            this.value = value;
            this.datatype = type;
            this.timestamp = timestamp;
        }

        public override string ToString()
        {
            return string.Format("value: {0}, datatype: {1}, timestamp: {2}", value, datatype, timestamp);
        }
    }

    class Crossbar
    {
        // variable to connect to crossbar
        DefaultWampChannelFactory factory;
        IWampChannel channel;
        IWampClientConnectionMonitor monitor;
        IWampRealmServiceProvider services;

        // variable to store publications 	 
        private readonly Dictionary<string, ISubject<Payload>> publications = new Dictionary<string, ISubject<Payload>>();

        public void start()
        {
            factory = new DefaultWampChannelFactory();

            channel = factory.CreateJsonChannel("ws://host:8080/ws", "realm1");

            services = channel.RealmProxy.Services;

            monitor = channel.RealmProxy.Monitor;
            monitor.ConnectionBroken += OnClose;
            monitor.ConnectionError += OnError;
            monitor.ConnectionEstablished += OnConnection;

            // il tempo e' assolutamente necessario per farlo partire bene
            // channel.Open().Wait(5000);
            // services = channel.RealmProxy.Services;

            Func<Task> connect = async () =>
            {
                Console.WriteLine("Crossbar await channel.Open()...");
                await channel.Open();
                Console.WriteLine("Crossbar channel.Open() done");
            };

            WampChannelReconnector reconnector = new WampChannelReconnector(channel, connect);
            reconnector.Start();
        }

        private void OnClose(object sender, WampSessionCloseEventArgs e)
        {
            Console.WriteLine("Crossbar OnClose Reason:" + e.Reason);
        }

        private void OnError(object sender, WampConnectionErrorEventArgs e)
        {
            Console.WriteLine("Crossbar OnError Exception:" + e.Exception);
        }

        private void OnConnection(object sender, WampSessionCreatedEventArgs e)
        {
            Console.WriteLine("Crossbar OnConnection SessionId:" + e.SessionId);
        }

        // add a publication, set the subject and return the last value
        public string publish(string subject, Payload payload)
        {
            try
            {
                // read or create publisher
                ISubject<Payload> publisher;
                if (publications.ContainsKey(subject))
                    publisher = (ISubject<Payload>)publications[subject];
                else
                {
                    publisher = services.GetSubject<Payload>(subject);
                    publications[subject] = publisher;
                }
                // publish next value
                publisher.OnNext(payload);

                return payload.timestamp.ToString();
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }
        // Set up a simple configuration that logs on the console.
        // BasicConfigurator.Configure();

        // log.Info("Entering application.");
        public static void Main()
        {
            Crossbar crossbar = new Crossbar();
            crossbar.start();

            bool continua = true;
            //string subject = null;
            //string subject_str = null;
            while (continua)
            {
                {
                    Console.WriteLine("0=stop, 1=spara");
                    string tasto = Console.ReadLine();
                    Console.WriteLine("tasto = " + tasto);

                    if (tasto == "0")
                    {
                        continua = false;
                    }
                    else
                    {
                        Random rnd = new Random();
                        for (int j = 0; j < 1000000; j++)
                        {
                            for (int i = 0; i < 20000; i++)
                            {
                                int field = rnd.Next(1, 1000);
                                int value = field * 100000 + rnd.Next(1, 10000);
                                string subject = "TEST_" + tasto + "." + field.ToString();
                                Payload payload = new Payload(value, "double", DateTime.Now);
                                string ritorno = crossbar.publish(subject, payload);
                                Console.WriteLine(subject + ": " + value + " " + ritorno);
                            }
                            System.Threading.Thread.Sleep(1000);
                        }
                    }
                }
            }
        }
    }
}`

**Comment by darkl** [comment] 2016-03-18 10:17
Hi Simone,

Yes, WampSharp uses WebSocket4Net for websocket transport.

I tried running 4 instances of your program for 30 minutes and according to crossbar log, all instances kept publishing for all these 30 minutes.

Elad

**Comment by simpuc** [comment] 2016-03-22 12:51
Hi Elad,

As I supposed it is an environment issue. I have done more tests and my program works well on Windows Server 2012 R2, but it doesn't work on my Windows 7 pc. 
Probably it depends by different .NET installation libraries, but I think it will be like to look for a needle in a haystack.
If you have any suggestion I'll appreciate it, in the same time thank you very much for your help

Simone

**Comment by simpuc** [comment] 2016-04-05 12:08
Hi Elad,

only to inform you that using rawsocket this issue is resolved 

```
IWampChannel channel =
                factory.ConnectToRealm(Configuration.Instance.getCrossbar_realm())
                       .RawSocketTransport("LX000000010550", 8081)
                       .JsonSerialization()
                       .Build();
```

Thank you and best regards
Simone

**Comment by darkl** [comment] 2016-04-05 12:39
Hi Simone,

I'm happy to hear you've found a way to bypass the issue.

If using RawSocket resolves the problem, the problem probably is somehow
related to WebSocket4Net. (Probably related to the issue I referred
earlier).

Elad

**Comment by darkl** [comment] 2016-07-30 13:23
Closing since this seems to be a WebSocket4Net issue with old operating systems.

**Closed by darkl** 2016-07-30 13:23 UTC
Labels: bug, client, publisher
